### ISSUE TITLE
With initial profile file option, GLM seems to crash if depth settings do not match max depth

### ISSUE THREAD

**Issue by jorritmesman** [aemon-j/LakeEnsemblR#132]
When picking the option to provide an initial profile by file (i.e. not using the observations file), run_ensemble crashes for GLM when the maximum depth is more than the maximum depth of the lake, and if the maximum depth of the initial profile is shorter than the maximum lake depth, the function runs, but provides unrealistic output.

We probably need to find with what types of initial profile GLM still runs normally, and linearly interpolate the initial profile to that format. 

![GLM_output_init_prof](https://user-images.githubusercontent.com/42146440/80725538-7f973480-8b03-11ea-86b8-737b3882900b.png)

**Comment by jread-usgs** [comment]
this is when `lake_depth` is greater than `max(H) - min(H)`? 

We discussed a little if these types of parameter mismatches should be caught within something like `glmtools` or not. See https://github.com/USGS-R/glmtools/issues/261

**Comment by jorritmesman** [comment]
Yes, I think this is the issue. I haven't tested extensively yet, but when the deepest depth in the initial profile did not match `max(H) - min(H)`, things did not seem to work.

Thanks for the link to the glmtools issue. When we've found a solution, or more information, we'll post it here.

A solution LER would be to interpolate the bathymetry so that the last depth matches `max(H) - min(H)`

**Comment by jorritmesman** [comment]
This issue was handled in PR #149. If users enter an initial profile that is deeper than the actual depth of the lake, an error is thrown. We leave it to the user to fix the issue, as it is not clear if interpolation would be desired.

The "unrealistic output" that I referred to in the plot seemed to be related to the ncdf-viewer I was using, as I could not find the corresponding errors in the datasets (glmtools plotting function worked fine).
