### ISSUE TITLE
export_meteo gives error when cprecipitation column is missing

### ISSUE THREAD

**Issue by JFeldbauer** [aemon-j/LakeEnsemblR#136]
In the wiki and vignette is written that the columns precipitation is optional, but if I run `export_meteo()` without a precipitation columns it will crash

**Comment by jorritmesman** [comment]
Fixed in PR #141. You can now provide either precipitation, or rainfall (or both). Precipitation is assumed to be rain + snow (snow in rainfall-equivalent).
