### ISSUE TITLE
Problem with input_yaml_multiple

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#155]
1. There is no documentation on how to use this function
2. If the value is empty in the LER yaml config file e.g. `file:` it deletes the line
3. Also if there are exponents e.g. 2.0E+4, it prints that it replaces the value but when you examine the file it has not been replaced.

Possible similar problems with input_yaml in gotmtools.
Would propose the use of NULL instead of empty values, clearer and is used in R so not unfamiliar with the user where yaml configuration might be.

**Comment by jorritmesman** [comment]
This issue got fixed in PR #161 (devel branch). A PR has been submitted to gotmtools to fix this issue in gotmtools::input_yaml as well.

The problem with the (positive) exponents related to the old value being interpreted as a regular expression. This no longer happens.
