### ISSUE TITLE
Using sea_level_pressure crashes

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#159]
If you provide sea level pressure instead of surface level pressure in the meteo file, export_config %>% export_meteo %>% format_met crashes. Currently, there is no catch for Sea Level pressure here.

A solution could just be to use that instead of surface pressure

**Comment by jorritmesman** [comment]
Fixed in PR #163 (devel). If surface pressure is not provided, but sea level pressure is, surface level is calculated using the barometric formula.
