### ISSUE TITLE
GOTM crashes when stop date is the last date of the met file.

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#167]
When running for 16 day forecast, GOTM crashes with:
```
FATAL ERROR: 
input::timeseries_file_update: End of file reached while attempting to read new data from meteo_file.dat. Does this file span the entire simulated period?"
```
when the stop date in gotm.yaml = last date in the met file. This is a model specific issue as all other 4 models run fine. A warning could be added to the check file maybe?

**Comment by jorritmesman** [comment]
Fixed in PR #177 (devel). In case stop date in gotm.yaml = last date in the met file, an extra time step is added to the GOTM met file in export_meteo. If this happens, a warning is thrown.
