### ISSUE TITLE
input_yaml_multiple doesn't check match of all keys

### ISSUE THREAD

**Issue by JFeldbauer** [aemon-j/LakeEnsemblR#187]
the input_yaml_multiple() function does not check if all keys are matched, this can lead to undesired results and model behaviour which is hard to debug. E.g. the key "method" appears several times in the GOTM yaml file and this issue can lead to changing the method at the wrong/an unintended space...

**Comment by jorritmesman** [comment]
This was fixed in PR #188 and #189. Now the function throws an error if you try to change a key that does not occur in the right section.
