### ISSUE TITLE
Problem installing MyLakeR

### ISSUE THREAD

**Issue by rptacnik** [aemon-j/LakeEnsemblR#213]
Hi,
I could install everything suggested through devtools(rLakeAnalyzer....SimstratR), but can install MylakeR. (Same error I get for LakeEnsemblR).
Can you help? 
---
R version 4.0.3 (2020-10-10) 
---
Downloading GitHub repo aemon-j/MyLakeR@HEAD
√  checking for file 'C:\Users\ptacnik\AppData\Local\Temp\RtmpsnBc7C\remotes31c46cbc77cb\aemon-j-MyLakeR-0cc1d2f/DESCRIPTION' ...
-  preparing 'MyLakeR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'MyLakeR_0.0.1.tar.gz'
   
Installing package into ‘C:/Users/ptacnik/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'MyLakeR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'stats::filter' by 'dplyr::filter' when loading 'gotmtools'
Error: object 'get_yaml_value' is not exported by 'namespace:gotmtools'
Execution halted
ERROR: lazy loading failed for package 'MyLakeR'
* removing 'C:/Users/ptacnik/Documents/R/win-library/4.0/MyLakeR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/ptacnik/AppData/Local/Temp/RtmpsnBc7C/file31c451add97/MyLakeR_0.0.1.tar.gz’ had non-zero exit status

**Comment by JFeldbauer** [comment]
Hello,
I tried to replicate your problem by installing LakeEnsemnblR on a fresh machine but could not reproduce it. But I am using Linux and currently don't have access to a windows machine, so it could be related to that. In any case this is a strange error.
As the error seems to be related to gotmtools could you try to remove and re-install gotmtools, e.g. by using:
```
remove.packages("gotmtools")
devtools::install_github("aemon-j/gotmtools")
```
let me know if this helps.
All the best, Johannes

**Comment by rptacnik** [comment]
Thanks for your fast reply!...I did what you suggested...it did the trick ;-)

**Comment by JFeldbauer** [comment]
perfect! glad I could help
