### ISSUE TITLE
 FATAL ERROR: gotm.yaml is invalid

### ISSUE THREAD

**Issue by rptacnik** [aemon-j/LakeEnsemblR#214]
When running the example model run, I get an error related to the file "gotm.yaml" file:
 ERROR: the following setting(s) were not recognized:
 - /surface/longwave_radiation
 FATAL ERROR: gotm.yaml is invalid.

----
> run_ensemble(config_file = config_file, model = model)
Loading water temperature observations...[2021-01-12 15:15:10]
Finished loading water temperature observations![2021-01-12 15:15:10]
Running models... (Have you tried parallelizing?) [2021-01-12 15:15:11]
FLake run is complete! [2021-01-12 15:15:11]
GLM run is complete! [2021-01-12 15:15:11]
 ------------------------------------------------------------------------
 GOTM started on 2021/01/12 at 15:15:12
 ------------------------------------------------------------------------
    init_gotm
 ------------------------------------------------------------------------
        Reading yaml configuration from: gotm.yaml
        configuring modules ....
    init_airsea_yaml
        done
    init_stim_yaml
        done.
    init_observations_yaml
    configure_streams_yaml
        done
    init_turbulence_yaml
        done.
    configure_gotm_fabm
        done.
    init_meanflow_yaml
        done
    init_eqstate_yaml
        done.
 WARNING: /output will be ignored because output.yaml is present.
        GOTM Simulation
        Using           94  layers to resolve a depth of   46.8000000000000     
        The station Feeagh is situated at (lat,long)    53.9000000000000     
  -9.50000000000000     
        Feeagh
        initializing modules....
    init_input
        done
    init_time
        Time step:         3600.00000000000       seconds
        Time format:               2
        Start:          2010-01-01 00:00:00
        Stop:           2011-01-01 00:00:00
         ==>          365  day(s) and                      0  seconds ==> 
                  8760  micro time steps
    post_init_meanflow
        allocation meanflow memory..
        done.
    init_hypsograph
        reading hypsograph from:
            hypsograph.dat
            # of lines          48 read order           2
    init_tridiagonal
        sigma coordinates (zooming possible)
    post_init_observations
        allocation observation memory..
            none
        Reading /temperature from:
            init_cond.dat
        Using constant /mimic_3d/ext_pressure/h=   0.000000000000000E+000
        Using constant /mimic_3d/ext_pressure/dpdx=   0.000000000000000E+000
        Using constant /mimic_3d/ext_pressure/dpdy=   0.000000000000000E+000
        extinction method
        Using constant /light_extinction/A=   0.550000000000000     
        Using constant /light_extinction/g1=   0.500000000000000     
        Using constant /light_extinction/g2=    1.02040816326531     
        Using constant /mimic_3d/w/height=   0.000000000000000E+000
        Using constant /mimic_3d/zeta=   0.000000000000000E+000
        Using constant /surface/wave/Hs=   0.000000000000000E+000
        Using constant /surface/wave/Tz=   0.000000000000000E+000
        Using constant /surface/wave/phiw=   0.000000000000000E+000
        done.
    post_init_streams
        Reading /streams/outflow/flow from:
            outflow_file.dat
        Using constant /streams/outflow/temp=   -1.00000000000000     
        Using constant /streams/outflow/salt=   -1.00000000000000     
        Reading /streams/inflow/flow from:
            inflow_file.dat
        Reading /streams/inflow/temp from:
            inflow_file.dat
        Reading /streams/inflow/salt from:
            inflow_file.dat
            
 Only one set of profiles is present in init_cond.dat. These will be used throug
 hout the simulation
    post_init_turbulence
        allocation turbulence memory..
        done.
         
        --------------------------------------------------------
        You are using the k-epsilon model
        with the following properties:
         
            ce1                                  =   1.44000000000000     
            ce2                                  =   1.92000000000000     
            ce3minus                             = -0.620912126249001     
            ce3plus                              =   1.00000000000000     
            sig_k                                =   1.00000000000000     
            sig_e                                =   1.20265265449834     
         
            Value of the stability function
            in the log-law,                   cm0 =  0.526464710835324     
            in shear-free turbulence,        cmsf =  0.731006013490010     
         
            von Karman constant,           kappa =  0.400000000000000     
            homogeneous decay rate,            d =  -1.08695652173913     
            spatial decay rate (no shear), alpha =  -7.82461519721494     
            length-scale slope (no shear),     L =  4.662134571526330E-002
            steady-state Richardson-number, Ri_st=  0.250000000000000     
        --------------------------------------------------------
         
    post_init_airsea
        Reading /surface/meteo/swr from:
            meteo_file.dat
        Reading /surface/meteo/u10 from:
            meteo_file.dat
        Reading /surface/meteo/v10 from:
            meteo_file.dat
        Reading /surface/meteo/airp from:
            meteo_file.dat
        Reading /surface/meteo/airt from:
            meteo_file.dat
        Reading /surface/meteo/hum from:
            meteo_file.dat
        Reading /surface/meteo/cloud from:
            meteo_file.dat
        Air-sea exchanges will be calculated
            heat- and momentum-fluxes:
                using Fairall et. all formulation
            long-wave back radiation:
                using Clark formulation
        Reading /surface/meteo/precip from:
            meteo_file.dat
        rain_impact=       T
        calc_evaporation=  T
        Using constant /surface/sst=   0.000000000000000E+000
        Using constant /surface/sss=   0.000000000000000E+000
        done
    post_init_stim
        done.
    register_all_variables()
        register_coordinate_variables()
        register_meanflow_variables()
        register_airsea_variables()
        register_stim_variables()
        register_observation_variables()
        register_stream_variables()
        register_turbulence_variables()
        register_diagnostic_variables()
 ERROR: the following setting(s) were not recognized:
 - /surface/longwave_radiation
 FATAL ERROR: gotm.yaml is invalid.
1
GOTM run is complete! [2021-01-12 15:15:12]
Error in R_nc4_open: No such file or directory
Error in nc_open(ncdf) : 
  Error in nc_open trying to open file ./GOTM/output/output.nc

**Comment by JFeldbauer** [comment]
Hello,
I tried to reproduce the error but again did not manage to do so. Did you try the example data following these lines of code:
```
# Load LakeEnsemblR
library(LakeEnsemblR)

# Copy template folder
template_folder <- system.file("extdata/feeagh", package= "LakeEnsemblR")
dir.create("example") # Create example folder
file.copy(from = template_folder, to = "example", recursive = TRUE)
setwd("example/feeagh") # Change working directory to example folder

# Set config file & models
config_file <- 'LakeEnsemblR.yaml'
model <- c("FLake", "GLM", "GOTM", "Simstrat", "MyLake")

# Example run
# 1. Export settings - creates directories with all model setups and exports settings from the LER configuration file
export_config(config_file = config_file, model = model)

# 2. Run ensemble lake models
run_ensemble(config_file = config_file, model = model)

```

or did you use your own data? From the look of the error I would think there is some problem with the format of your forcing data

**Comment by rptacnik** [comment]
Hei Johannes,


sorry to bother you again...


I only tried running the example as provided on github. I get the same when I run the script you sent in your reply. I append the ourtut below


there is a warning in the beginning, dont know it matters. Otherwise, an error is only reported in the end

Warning message:
replacing previous import ‘stats::filter’ by ‘dplyr::filter’ when loading ‘gotmtools’


cheers

Robert


> library(LakeEnsemblR)


  _          _        _____                          _     _ ____
 | |    __ _| | _____| ____|_ __  ___  ___ _ __ ___ | |__ | |  _ \
 | |   / _` | |/ / _ |  _| | '_ \/ __|/ _ | '_ ` _ \| '_ \| | |_) |
 | |__| (_| |   |  __| |___| | | \__ |  __| | | | | | |_) | |  _ <
 |_____\__,_|_|\_\___|_____|_| |_|___/\___|_| |_| |_|_.__/|_|_| \_\


              https://github.com/aemon-j/LakeEnsemblR
LakeEnsemblR version 1.0.0 (2020-09-09) is loaded
Warning message:
replacing previous import ‘stats::filter’ by ‘dplyr::filter’ when loading ‘gotmtools’
> template_folder <- system.file("extdata/feeagh", package= "LakeEnsemblR")
> dir.create("example") # Create example folder
> file.copy(from = template_folder, to = "example", recursive = TRUE)
[1] TRUE
> setwd("example/feeagh") # Change working directory to example folder
> config_file <- 'LakeEnsemblR.yaml'
> model <- c("FLake", "GLM", "GOTM", "Simstrat", "MyLake")
> export_config(config_file = config_file, model = model)
export_dirs complete!
Replaced time start 2010-01-0100:00:00 with 2010-01-01 00:00:00
Replaced time stop 2011-01-0100:00:00 with 2011-01-01 00:00:00
Replaced time dt 86400 with 3600
Replaced Simulation Start year 2010, with 2010
Replaced Simulation Start d 0, with 0
Replaced Simulation End d 365, with 365
Replaced Simulation Timestep s 86400, with 3600
export_time complete!
Replaced SIMULATION_PARAMS h_ML_in 16.05, with 16.05
Replaced LAKE_PARAMS depth_w_lk 16.05, with 16.05
Replaced LAKE_PARAMS latitude_lk 53.9, with 53.9
Replaced location name Feeagh with Feeagh
Replaced location latitude 53.9 with 53.9
Replaced location longitude -9.5 with -9.5
Replaced location depth 46 with 46.8
Replaced grid nlev 100 with 94
Replaced ice model 0 with 2
Replaced location hypsograph hypsograph.dat with hypsograph.dat
Replaced Input Grid 92, with 94
Replaced Input Morphology "hypsograph.dat", with "hypsograph.dat"
Replaced ModelParameters lat 53.9, with 53.9
Replaced ModelConfig IceModel 1, with 1
Replaced ModelParameters a_seiche 0.003, with 0.00362056367218844
export_location complete!
Replaced METEO outputfile 'output/output.dat', with 'output/output.dat'
Replaced output time_step 1 with 24
Replaced output time_unit day with hour
Replaced output time_method mean with mean
Replaced output format netcdf with netcdf
Replaced Output Path "output", with "output"
Replaced Output Depths 0.5, with 0.5
Replaced Output Times 1, with 24
export_output_settings complete!
Loading met data...[2021-01-12 15:45:59]
Finished loading met data![2021-01-12 15:45:59]
Replaced SIMULATION_PARAMS del_time_lk 86400, with 86400
Replaced SIMULATION_PARAMS time_step_number 366, with 365
Replaced METEO meteofile 'meteo_file.dat', with 'all_meteo_file.dat'
FLake: Created file ./FLake/all_meteo_file.dat
GLM: Created file ./GLM/meteo_file.csv
Replaced u10 column 1 with 1
Replaced u10 scale_factor 1 with 1
Replaced v10 column 2 with 2
Replaced v10 scale_factor 1 with 1
Replaced airp column 3 with 3
Replaced airp scale_factor 1 with 1
Replaced airt column 4 with 4
Replaced airt scale_factor 1 with 1
Replaced cloud column 6 with 6
Replaced cloud scale_factor 1 with 1
Replaced swr column 7 with 7
Replaced swr scale_factor 1 with 1
Replaced precip column 8 with 8
Replaced precip scale_factor 1 with 1
Replaced hum column 5 with 5
Replaced hum type 1 with 1
Replaced hum scale_factor 1 with 1
Replaced u10 file meteo_file.dat with meteo_file.dat
Replaced v10 file meteo_file.dat with meteo_file.dat
Replaced airp file meteo_file.dat with meteo_file.dat
Replaced airt file meteo_file.dat with meteo_file.dat
Replaced cloud file meteo_file.dat with meteo_file.dat
Replaced swr file meteo_file.dat with meteo_file.dat
Replaced precip file meteo_file.dat with meteo_file.dat
Replaced hum file meteo_file.dat with meteo_file.dat
GOTM: Created file ./GOTM/meteo_file.dat
Replaced ModelConfig SnowModel 1 with 1
Replaced ModelParameters p_air 1011, with 1012
Replaced ModelConfig Forcing 5, with 5
Replaced Input Forcing "meteo_file.dat", with "meteo_file.dat"
Simstrat: Created file ./Simstrat/meteo_file.dat
MyLake: Created file ./MyLake/meteo_file.dat
export_meteo complete!
Loading wtemp_file...
Replaced SIMULATION_PARAMS T_wML_in 6.128, with 4.977
Replaced SIMULATION_PARAMS T_bot_in 6.255, with 4.905
Replaced SIMULATION_PARAMS h_ML_in 16.05, with 16.05
FLake: Input initial conditions into ./FLake/flake.nml
GLM: Input initial conditions into ./GLM/glm3.nml
Replaced temperature file init_cond.dat with init_cond.dat
Replaced temperature method 2 with 2
Replaced temperature column 1 with 1
GOTM: Created initial conditions file ./GOTM/init_cond.dat
Replaced Input Initial conditions "init_cond.dat", with "init_cond.dat"
Simstrat: Created initial conditions file ./Simstrat/init_cond.dat
MyLake: Created initial conditions file ./MyLake/mylake.Rdata
   depths wtemp
1     0.9 4.977
2     2.5 4.965
3     5.0 4.953
4     8.0 4.941
5    11.0 4.883
6    14.0 4.887
7    16.0 4.877
8    18.0 4.986
9    20.0 4.960
10   22.0 4.944
11   27.0 4.980
12   32.0 4.951
13   42.0 4.905
export_init_cond complete!
Replaced TRANSPARENCY extincoef_optic 1.5, with 0.98
Replaced g2 method 0 with 0
Replaced g2 constant_value 2.0 with 1.02040816326531
Replaced Input Absorption "light_absorption.dat", with "light_absorption.dat"
export_extinction complete!
Replaced inflow Qfromfile .true., with .true.
Replaced streams inflow flow method: 2 with 2
Replaced streams inflow temp method: 2 with 2
Replaced streams inflow salt method: 2 with 2
Replaced streams outflow flow method: 0 with 0
Replaced streams outflow temp method: 0 with 0
Replaced streams outflow salt method: 0 with 0
Loading inflow data...
Replaced inflow time_step_number 1653 with 366
FLake: Created file ./FLake/Tinflow
FLake does not need outflows, as mass fluxes are not considered.
GLM: Created file ./GLM/inflow_file.csv
GLM: Created outflow file ./GLM/outflow.csv
GOTM: Created file ./GOTM/inflow_file.dat
Replaced streams outflow flow method: 0 with 2
Replaced streams outflow temp method: 0 with 0
Replaced streams outflow salt method: 0 with 0
GOTM: Created outflow file ./GOTM/outflow_file.dat
Simstrat: Created file ./Simstrat/Qin.dat
Simstrat: Created outflow file ./Simstrat/Qout.dat
MyLake: Created file ./MyLake/mylake.Rdata
MyLake does not need specific outflows, as it employs automatic overflow.
export_inflow complete!
Replaced  fetch_lk 2000.0, with 2000
Replaced  bsn_len 3163.891 with 3678
Replaced  bsn_wid 1581.946 with 944
Replaced  k_min 3.60000000E-06 with 3.6e-06
Replaced Phys.par C_shelter 0.692506090980988 with 0.15
export_model_parameters complete!
> run_ensemble(config_file = config_file, model = model)
Loading water temperature observations...[2021-01-12 15:46:15]
Finished loading water temperature observations![2021-01-12 15:46:15]
Running models... (Have you tried parallelizing?) [2021-01-12 15:46:15]
FLake run is complete! [2021-01-12 15:46:15]
GLM run is complete! [2021-01-12 15:46:16]
 ------------------------------------------------------------------------
 GOTM started on 2021/01/12 at 15:46:16
 ------------------------------------------------------------------------
    init_gotm
 ------------------------------------------------------------------------
        Reading yaml configuration from: gotm.yaml
        configuring modules ....
    init_airsea_yaml
        done
    init_stim_yaml
        done.
    init_observations_yaml
    configure_streams_yaml
        done
    init_turbulence_yaml
        done.
    configure_gotm_fabm
        done.
    init_meanflow_yaml
        done
    init_eqstate_yaml
        done.
 WARNING: /output will be ignored because output.yaml is present.
        GOTM Simulation
        Using           94  layers to resolve a depth of   46.8000000000000
        The station Feeagh is situated at (lat,long)    53.9000000000000
  -9.50000000000000
        Feeagh
        initializing modules....
    init_input
        done
    init_time
        Time step:         3600.00000000000       seconds
        Time format:               2
        Start:          2010-01-01 00:00:00
        Stop:           2011-01-01 00:00:00
         ==>          365  day(s) and                      0  seconds ==>
                  8760  micro time steps
    post_init_meanflow
        allocation meanflow memory..
        done.
    init_hypsograph
        reading hypsograph from:
            hypsograph.dat
            # of lines          48 read order           2
    init_tridiagonal
        sigma coordinates (zooming possible)
    post_init_observations
        allocation observation memory..
            none
        Reading /temperature from:
            init_cond.dat
        Using constant /mimic_3d/ext_pressure/h=   0.000000000000000E+000
        Using constant /mimic_3d/ext_pressure/dpdx=   0.000000000000000E+000
        Using constant /mimic_3d/ext_pressure/dpdy=   0.000000000000000E+000
        extinction method
        Using constant /light_extinction/A=   0.550000000000000
        Using constant /light_extinction/g1=   0.500000000000000
        Using constant /light_extinction/g2=    1.02040816326531
        Using constant /mimic_3d/w/height=   0.000000000000000E+000
        Using constant /mimic_3d/zeta=   0.000000000000000E+000
        Using constant /surface/wave/Hs=   0.000000000000000E+000
        Using constant /surface/wave/Tz=   0.000000000000000E+000
        Using constant /surface/wave/phiw=   0.000000000000000E+000
        done.
    post_init_streams
        Reading /streams/outflow/flow from:
            outflow_file.dat
        Using constant /streams/outflow/temp=   -1.00000000000000
        Using constant /streams/outflow/salt=   -1.00000000000000
        Reading /streams/inflow/flow from:
            inflow_file.dat
        Reading /streams/inflow/temp from:
            inflow_file.dat
        Reading /streams/inflow/salt from:
            inflow_file.dat

 Only one set of profiles is present in init_cond.dat. These will be used throug
 hout the simulation
    post_init_turbulence
        allocation turbulence memory..
        done.

        --------------------------------------------------------
        You are using the k-epsilon model
        with the following properties:

            ce1                                  =   1.44000000000000
            ce2                                  =   1.92000000000000
            ce3minus                             = -0.620912126249001
            ce3plus                              =   1.00000000000000
            sig_k                                =   1.00000000000000
            sig_e                                =   1.20265265449834

            Value of the stability function
            in the log-law,                   cm0 =  0.526464710835324
            in shear-free turbulence,        cmsf =  0.731006013490010

            von Karman constant,           kappa =  0.400000000000000
            homogeneous decay rate,            d =  -1.08695652173913
            spatial decay rate (no shear), alpha =  -7.82461519721494
            length-scale slope (no shear),     L =  4.662134571526330E-002
            steady-state Richardson-number, Ri_st=  0.250000000000000
        --------------------------------------------------------

    post_init_airsea
        Reading /surface/meteo/swr from:
            meteo_file.dat
        Reading /surface/meteo/u10 from:
            meteo_file.dat
        Reading /surface/meteo/v10 from:
            meteo_file.dat
        Reading /surface/meteo/airp from:
            meteo_file.dat
        Reading /surface/meteo/airt from:
            meteo_file.dat
        Reading /surface/meteo/hum from:
            meteo_file.dat
        Reading /surface/meteo/cloud from:
            meteo_file.dat
        Air-sea exchanges will be calculated
            heat- and momentum-fluxes:
                using Fairall et. all formulation
            long-wave back radiation:
                using Clark formulation
        Reading /surface/meteo/precip from:
            meteo_file.dat
        rain_impact=       T
        calc_evaporation=  T
        Using constant /surface/sst=   0.000000000000000E+000
        Using constant /surface/sss=   0.000000000000000E+000
        done
    post_init_stim
        done.
    register_all_variables()
        register_coordinate_variables()
        register_meanflow_variables()
        register_airsea_variables()
        register_stim_variables()
        register_observation_variables()
        register_stream_variables()
        register_turbulence_variables()
        register_diagnostic_variables()
 ERROR: the following setting(s) were not recognized:
 - /surface/longwave_radiation
 FATAL ERROR: gotm.yaml is invalid.
1
GOTM run is complete! [2021-01-12 15:46:16]
Error in R_nc4_open: No such file or directory
Error in nc_open(ncdf) :
  Error in nc_open trying to open file ./GOTM/output/output.nc






________________________________

**Comment by JFeldbauer** [comment]
can you please post the output of:
`GOTMr::run_gotm(".", args = "--version", verbose = T)`

**Comment by rptacnik** [comment]
> GOTMr::run_gotm(".", args = "--version", verbose = T)
[1] " ------------------------------------------------------------------------"
[2] " GOTM:    5.4.0 (unknown branch)"
[3] " YAML:    0.1.0 (unknown branch)"
[4] " flexout: 0.1.0 (unknown branch)"
[5] " STIM:     (unknown branch)"
[6] " FABM:    unknown (unknown branch)"
[7] " NetCDF: 3.6.1-beta1 of Mar  7 2018 17:17:53 $"
[8] " ------------------------------------------------------------------------"
[9] " Compiler: Intel 19.0.0.20181018"
>



________________________________

**Comment by JFeldbauer** [comment]
We are able to run the example using the same GOTM version. But the error suggests that you might be using an older GOTM version as they changed the name in the GOTM control file (usually gotm.yaml) from "back_radiation" to "longwave_radiation". Do you have another version of GOTM installed on your computer?

**Comment by tadhg-moore** [comment]
I just did a fresh install of GOTMr on my Windows system and for my version I got:
```
 [1] " ------------------------------------------------------------------------"
 [2] " GOTM:    5.4.0 (unknown branch)"                                         
 [3] " YAML:    0.1.0 (unknown branch)"                                         
 [4] " flexout: 0.1.0 (unknown branch)"                                         
 [5] " STIM:     (unknown branch)"                                              
 [6] " FABM:    unknown (unknown branch)"                                       
 [7] " WET:  unknown (unknown branch)"                                          
 [8] " NetCDF: 3.6.1-beta1 of Mar  7 2018 17:17:53 $"                           
 [9] " ------------------------------------------------------------------------"
[10] " Compiler: Intel 19.0.0.20180804"    
```
And it was able to run the example.
Which OS system are you using? Mac, Linux or Windows?

**Comment by JFeldbauer** [comment]
It seem the version Tadhg uses (the one from github.com/aemon-j/GOTMr) is slightly different, see the additional WET entry and the Compiler version.  Maybe you could try to re-install GOTMr.

Another possible solution would be to change "longwave_radiation" to "back_radiation" in the surface section of the  GOTM control file which is located in the GOTM folder and called gotm.yaml.

**Comment by rptacnik** [comment]
Thanks for your feedback!
I reinstalled GOTMr as suggested, now I can run the example without errors!
@tadhg-moore  - my OS is win 10

cheers
Robert

**Comment by JFeldbauer** [comment]
good to hear and glad we could help
cheers, Johannes

**Comment by rptacnik** [comment]
I re-ran the diagnostics you provided me, now the WET entry exists (just fyi)

> GOTMr::run_gotm(".", args = "--version", verbose = T)
 [1] " ------------------------------------------------------------------------"
 [2] " GOTM:    5.4.0 (unknown branch)"                                         
 [3] " YAML:    0.1.0 (unknown branch)"                                         
 [4] " flexout: 0.1.0 (unknown branch)"                                         
 [5] " STIM:     (unknown branch)"                                              
 [6] " FABM:    unknown (unknown branch)"                                       
 [7] " WET:  unknown (unknown branch)"                                          
 [8] " NetCDF: 3.6.1-beta1 of Mar  7 2018 17:17:53 $"                           
 [9] " ------------------------------------------------------------------------"
[10] " Compiler: Intel 19.0.0.20180804"
