### ISSUE TITLE
Example now failing after update to R 4.1.1 and RStudio 2021.09.0 Build 351

### ISSUE THREAD

**Issue by jjvenky** [aemon-j/LakeEnsemblR#234]
After the update to R 4.1.1 and the necessary update of RStudio to 2021.09.0 Build 351, I had to reinstall all my R packages. This was fine (and expected) in Ubuntu 20.04.3 LTS.

Now, following the example from https://github.com/aemon-j/LakeEnsemblR/

```
> # 2. Run ensemble lake models
> run_ensemble(config_file = config_file, model = model)
Loading water temperature observations...[2021-11-02 14:05:21]
Finished loading water temperature observations![2021-11-02 14:05:22]
Running models... (Have you tried parallelizing?) [2021-11-02 14:05:22]
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './FLake/output/output.dat': No such file or directory
```
  
The folder './FLake/output' exists but the output.dat does not.

This looks like a workding directory problem but `getwd()` shows '/home/jvenkiteswaran/tmp/example/feeagh' so './FLake/output' makes sense.

**Comment by JFeldbauer** [comment]
I think this might be an issue with the shared libraries and the models not running as a consequence of this. This is described in the wiki (https://github.com/aemon-j/LakeEnsemblR/wiki/Installation-issues).

To be sure if this is the cause of the issue you can run the models on their own using the `run-model()` function from the model specific packages, e.g.

```
FLakeR::run_flake(sim_folder = "FLake", verbose = TRUE)
GLM3r::run_glm(sim_folder = "GLM", verbose = TRUE)
GOTMr::run_gotm(sim_folder = "GOTM", verbose = TRUE)
SimstratR::run_simstrat(sim_folder = "Simstrat", par_file = "simstrat.par", verbose = TRUE)
```

**Comment by robertladwig** [comment]
A quick fix for GLM3r would be to delete libm.so.6 inside the package, re-install it and try again

**Comment by JFeldbauer** [comment]
It should be enough to delet the libm.so.6 files in your local R installlation. This is usually located in your home dir e.g. `~/R/4.1/GLM3r/extbin/nixGLM`

**Comment by jjvenky** [comment]
Wild. I remove all four `libm.so.6` files and the models run.

```
./R/x86_64-pc-linux-gnu-library/4.1/GOTMr/extbin/nix/libm.so.6
./R/x86_64-pc-linux-gnu-library/4.1/FLakeR/extbin/nix/libm.so.6
./R/x86_64-pc-linux-gnu-library/4.1/GLM3r/extbin/nixGLM/libm.so.6
./R/x86_64-pc-linux-gnu-library/4.1/SimstratR/extbin/nix/libm.so.6
```

FTR the three versions of `libm.so.6` installed in the /lib folder(s) all have different md5sums:

```
4aaad6c988fb8f356db567c0bf8f0d2d  /lib/x86_64-linux-gnu/libm.so.6
b2c721e8b382f3719927210ab5de9fd5  /lib/i386-linux-gnu/libm.so.6
a403e6f0fdcd5afa42cd6d50b0a09247  /lib32/libm.so.6
```

**Comment by jjvenky** [comment]
I will add (before closing this issue) a note from RStudio about R 4.1 that might be worth noting that there is a new graphics engine https://blog.rstudio.com/2021/06/09/rstudio-v1-4-update-whats-new/ and this might cause some problems.

**Comment by tpetzoldt** [comment]
> Wild. I remove all four `libm.so.6` files and the models run.
> 
```
> ./R/x86_64-pc-linux-gnu-library/4.1/GOTMr/extbin/nix/libm.so.6
```

Thanks, I had the same issue with GOTM and after searching the net for + an hour, removing libm.so.6 did the job.
