### ISSUE TITLE
the input of specific humidity in the meteo file

### ISSUE THREAD

**Issue by zgcao** [aemon-j/LakeEnsemblR#283]
I understand that the current version used relative humidity as the input of simulation. Some dataset, e.g., ISIMIP3b climate-forcing data, provides specific humidity. I wonder whether we can use 2-m specific humidity (kg kg-1) as the meteo column in Lake EnsembIR.

**Comment by JFeldbauer** [comment]
Hello,
as described e.g. in the [wiki](https://github.com/aemon-j/LakeEnsemblR/wiki/2.-Setting-up-LakeEnsemblR#meteorological-data) LakeEnsembler requires either relative humidity or dew point temperature. So you would need to convert the specific humidity.
