### ISSUE TITLE
Add lake elevation to master config file

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#30]
Currently we are not accounting for lake elevation in GLM, can be added as another argument in the master_config file. And then subsequent changes in export_config and export_meteo as elevation is used in the cloud cover calculation.

**Comment by jorritmesman** [comment]
Elevation is now in the master config file, and export_config uses it to construct GLM's hypsograph settings, and format_met (inside export_meteo) uses it to calculate cloud cover.
