### ISSUE TITLE
Change input_nml() function name

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#31]
Currently input_nml() function exists in glmtools/gotmtools/LakeEnsemblR. The function in gotmtools is a copy from glmtools so this can be removed. The benefits of the one in LakeEnsemblR is that it preserves comments but need to change the name so it doesn't clash with glmtools

**Comment by jread-usgs** [comment]
I thought the glmtools one was `set_nml`?

**Comment by tadhg-moore** [comment]
Yes you are right sorry. That means we just need to delete the input_nml() from gotmtools.

**Comment by tadhg-moore** [comment]
Migrated input_nml to gotmtools #34
