### ISSUE TITLE
use compression on .nc files?

### ISSUE THREAD

**Issue by jread-usgs** [aemon-j/LakeEnsemblR#32]
Wonder if you'd consider compression on the outputs, since they can get quite large. We have a small discussion on nc compression here, including the relevant flags: https://github.com/USGS-R/lake-temperature-model-prep/issues/67

**Comment by tadhg-moore** [comment]
We are using the ncdf4 package and there is an argument in ncvar_def() for compression. It would be a good idea as when we go sub-daily and longer time series it is going to increase the file size exponentially. It could be added as an argument to run_ensemble()

**Comment by tadhg-moore** [comment]
This functionality was included in #53 where it has been added as an option in the config.yaml file in the output section.
