### ISSUE TITLE
Changing time step leads to wrong results

### ISSUE THREAD

**Issue by jorritmesman** [aemon-j/LakeEnsemblR#39]
When testing the Feeagh example with the standard timestep (3600 s), everything works well, but the results are wrong when this time step is changed. For example, see attached file when time step is set to 1800 seconds : only Simstrat's output looks good, the others either contain missing values (FLake, GOTM) or are unrealistic (GLM).

Of GLM it is known that the model is incapable to run with sub-hourly time steps (although it does not crash), and FLake can only run with the same time step as the meteorological forcing.

We still need to add code to match the user's choice of model time step and plotting the output, and/or error-handling in case the user tries to do something that is not possible (e.g. run GLM with sub-hourly time steps).

![Plot_Timestep_1800seconds](https://user-images.githubusercontent.com/42146440/71898724-53256a00-315a-11ea-8b06-79e985410a5b.png)

**Comment by jread-usgs** [comment]
Kind of a tangent to your post, but 

> e.g. run GLM with sub-hourly time steps

is this not possible already? I have to admit that I haven't tried to do this, but is there any limitation in the model that restricts this?

**Comment by jorritmesman** [comment]
In a project I'm involved in we tried to run GLM with sub-hourly data (10-minute). The model does not crash, but wrong results are given (as in the figure above). I'm not aware why it doesn't work, but it seems to be related to the GLM code indeed.

**Comment by robertladwig** [comment]
Oh wow, yeah GLM's ability to run sub-daily time steps was improved recently in v3.0.5, but it seems sub-hourly is just weird. 
But is there any reason to run a vertical 1D model on a time step below a hour? Is this even feasible? On the other hand, I totally agree with you that we should add a warning if a user tries to run sub-hourly simulations. 
For GLM, maybe we need to check how the driver data interpolation works on the sub-hourly scale.

**Comment by jorritmesman** [comment]
I'd say there can be good reason, especially when using HFM data and/or looking at short-term events. It is possible in GOTM and Simstrat, and I believe also in LAKE and LAKEoneD. But anyways, it would not be up to the LakeEnsemblR team to fix that, but rather to add a warning (or to set the time step to hourly if the user chooses a smaller time step, something in that direction).

**Comment by jread-usgs** [comment]
Yeah, and I guess in the case of GLM I was assuming the driver data would be provided at the resolution of the time-step so there wouldn't be sub-hourly distribution of the inputs. But I've never tested this part of GLM and don't have idea idea what happens there.

**Comment by jorritmesman** [comment]
Changing time step settings (whether integration time step, meteo time step, or output time step) is now correctly handled by LakeEnsemblR. Fixes in #103, #106, and #108. 

So far no restrictions on GLM time step settings, as we have not yet figured out exactly when bad results are reproduced. This might follow later.
