### ISSUE TITLE
Add further outputs to ensemble_output.nc4

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#44]
Look at  other common variables between models and include them in the output, especially ice height. This also will tie in with #32 as compression will be needed once we start expanding our number of outputs.

**Comment by tadhg-moore** [comment]
I have currently added ice functionality during #53 , potentially heat fluxes next (Qe, Qh and Qb).

**Comment by tadhg-moore** [comment]
I think it would be useful to include bathymetry within the output as well to facilitate easier post-processing.

**Comment by tadhg-moore** [comment]
Also check if there is a difference between '.nc' or '.nc4' file extension as we could just name it '.nc'

**Comment by jorritmesman** [comment]
The new create_netcdf_output function (currently 2020-03-06 only on my fork) put the creation of netcdf output in run_ensemble in its own function. It is flexible to add other variables than ice and temperature, although the same format as ice_list and temp_list should be followed. Add the new list (e.g. list_buoyancy_frequency) to all_lists, and it should go right.

**Comment by tadhg-moore** [comment]
That sounds like it covers all these. Maybe rename the function to just 'create_netcdf'? As there are no other kinds of netCDF we are creating (yet).

**Comment by jorritmesman** [comment]
I was more thinking of later adding a function called "create_text_output", that's why I included the "_output" part. And I feel it's a bit more explanatory of what the function does?

**Comment by tadhg-moore** [comment]
Good point! I think it is my lazy side which tries to minimize everything. When this is merged with the master will we close this?

**Comment by jorritmesman** [comment]
After latest PR #110, the create_output_netcdf function is added to the master branch, and it should now be a lot easier to add output to the netcdf.

No new output has been added yet, but since that is more of an enhancement rather than an issue, I will close the Issue and move this topic to the new "Enhancements" project in the Project Tracker
