### ISSUE TITLE
Add daily dis-aggregation functionality to `export_met()`

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#45]
Include basic set of functions for dis-aggregating daily met data to hourly. Tom Shatwell has a few simple functions to do this. Could be added as an argument `daily2hourly = TRUE`. This is important particularly for short-wave radiation because of it's strong diel cycle.

**Comment by jorritmesman** [comment]
Since this is more of an enhancement rather than an issue, we decided to close the Issue and move it to the "Enhancements" project in the Project Tracker.
