### ISSUE TITLE
Standardise file naming scheme in the LHC functions

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#50]
Currently output from the LHC are time stamped. It should be adjusted that the 'params', 'calibration_results' and 'sa_results' file carry the same time stamp. Also to develop a standard name for each.

**Comment by jorritmesman** [comment]
Since this Issue relates to improvements to the calibration procedure rather than to errors in the code, we decided to move this topic to the project "Refactoring calibration scripts" in the Project Tracker, and close the Issue.
