### ISSUE TITLE
honor order of models called in functions

### ISSUE THREAD

**Issue by jread-usgs** [aemon-j/LakeEnsemblR#52]
Right now the flow control of how the models are called hard-codes the order they are run in. This is fine, but probably not what the user would think would be happening (e.g., if I specify one model before another, I'd expect the function to run that model first). 

Would you consider a PR that makes it so the order of the input args for models is retained for running them?

**Comment by tadhg-moore** [comment]
Yeah I think that would be a good feature to have if you have it coded up.
