### ISSUE TITLE
LakeEnsemblR install problem with ref = 'atom'

### ISSUE THREAD

**Issue by jjvenky** [aemon-j/LakeEnsemblR#54]
The instauctions in README.md show:

`devtools::install_github('aemon-j/LakeEnsemblR', ref = 'atom')`

But this fails with:

> error: Failed to install 'unknown package' from GitHub:
>   HTTP error 404.
>   No commit found for the ref atom

This means that `atom`must exist as an item. From the `devtools::install_github` documentation:

`Desired git reference. Could be a commit, tag, or branch name, or a call to github_pull. Defaults to "master".`

**Comment by tadhg-moore** [comment]
This was a result of legacy code in the README file.
