### ISSUE TITLE
time_step for GLM and Simstrat as days not hours

### ISSUE THREAD

**Issue by rmpilla** [aemon-j/LakeEnsemblR#56]
The new yaml configuration has a place for time_step (number) and time_unit, but for GLM and Simstrat these look to be imported as days if time_step=24 even if time_unit=hours. Doesn't seem to be a problem for FLake, GOTM, or MyLake, perhaps because those default to 1-day output (I know MyLake does, so these yaml values aren't even used for MyLake configuration). I noticed this when I was adding MyLake to the LakeEnsemblR code (see jpeg at https://github.com/rmpilla/LakeEnsemblR/tree/mylaker).

**Comment by tadhg-moore** [comment]
Found the issue, the updated yaml config file was missing an underscore in model-timestep. I have fixed this and submitted a pull request to your branch. If you are happy with it you can do a pull-request to the main branch.

**Comment by tadhg-moore** [comment]
#61 included this fix
