### ISSUE TITLE
run_LHC() output is written to 'model/output' - should be changed to its own folder

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#60]
Since a recent push, 'unlink' was added to delete old output in the folder just before the model is called, this was to ensure that old model output was not read in as results. But currently `run_LHC()` writes its output to this folder. I propose that this be changed so calibration has its own output foler e.g. model/calib_output

**Comment by robertladwig** [comment]
would it then make sense to have a structure like 
output --> output/model/
           --> output/calibration/  ?

**Comment by tadhg-moore** [comment]
Do you mean:
feeagh/output/model/ensemble_output.nc
and
feeagh/output/calibration/LHS_fit_xxxxxxxx.csv?

On further thinking, could we add the calibration output to the netCDF? Or would that risk being overwritten and not as easily accessible?

**Comment by jorritmesman** [comment]
Since this topic relates to improving the calibration procedure and not to errors in the current code, we decided to move this topic to the "Refactoring calibration scripts" project in the Project Tracker and close the Issue.
