### ISSUE TITLE
Simstrat output option

### ISSUE THREAD

**Issue by JFeldbauer** [aemon-j/LakeEnsemblR#65]
In the template Simstrat config file simstrat_template.par not all variables (especially ice is missing) are returned as output, which causes run_ensemble to crash. A possible fix could be to set
 `"All"   : true,` in line 18 of the config file.

**Comment by tadhg-moore** [comment]
One of the current 'issues' with Simstrat is that it can be relatively slow when writing all the output. This can be frustrating particularly when running the calibration. Ideally it would take what is specified in the output section of the yaml e.g. temp, ice, all and input it from there so it can run efficiently and what the user requires.

**Comment by jorritmesman** [comment]
This setting in Simstrat does not appear to be working in the current version (at least on Windows, where with All: ["T"] still all files are written to output).

Regardless, when all output is printed, the model still runs (not too slow) and optimizing runtime by restricting output (in Simstrat, or any model) would be more an enhancement than an issue. Therefore, we decided to close this Issue and move it to the "Enhancements" project in the Project Tracker.
