### ISSUE TITLE
Add testing suite to package development?

### ISSUE THREAD

**Issue by jread-usgs** [aemon-j/LakeEnsemblR#68]
Right now there aren't tests in the package, which makes it hard to know if you've broken something that someone else wrote. Perhaps invest in creating tests and including test to run locally (or through continuous integration for github PRs)?

**Comment by tadhg-moore** [comment]
I agree this is important. I use the code from the README file when testing so we could incorporate some of that into the code as examples. And I really like the idea of continuous integration but I don't have any experience with setting it up.

**Comment by robertladwig** [comment]
After #81 running R CMD check it gives only one error when checking examples ('LakeEnsemblR-Ex.R', but that file doesn't exit, does it?
