### ISSUE TITLE
Adding benchmark model 

### ISSUE THREAD

**Issue by robertladwig** [aemon-j/LakeEnsemblR#73]
I'm proposing to add a benchmark option to run_ensemble (benchmark = TRUE, with the default being off) that would run an additional simple lake model (e.g. simple two-layer model with diffusion approach). We could then compare the performance of the lake models first against observed data and against the simplified benchmark to identify weaknesses or uncertainties. One could then argue for example that model A underestimates vertical transport compared to model B, but both outperform the benchmark.

**Comment by tadhg-moore** [comment]
This is a good idea but would depend on the model. I kind of already see FLake as the benchmark model due to it's limitations, but this would be a good way to try and capture process error.
Are there any simple two-layer diffusion models out there?

**Comment by robertladwig** [comment]
I recently built a simple model using a text book, but didn't test it on real data yet. The files are here https://github.com/robertladwig/thermod

**Comment by tadhg-moore** [comment]
Here are a couple examples from hydrology:
Gong et al. 2013 https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1002/wrcr.20161
&
Beven, 2018 https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1002/wrcr.20161

They discuss these ideas of benchmarking and falsifying model hypotheses. This approach would fit in here. Exploring the ideas of quantification of uncertainty within models.

**Comment by robertladwig** [comment]
I think the idea of adding a purely data-based machine learning approach to LER, then calculate some information criteria and drop numerical models that were outperformed by the data-based approach sounds very cool.

**Comment by jorritmesman** [comment]
This has not been implemented yet, but because this is more of an enhancement than an Issue, we decided to move this idea to the "Enhancements" project in the Project Tracker and close the Issue.
