### ISSUE TITLE
Changing run_LHC and run_MCMC

### ISSUE THREAD

**Issue by robertladwig** [aemon-j/LakeEnsemblR#78]
We should modify run_LHC and run_MCMC to make it similar to the updated run_ensemble function, plus we need to add MyLake to it.

**Comment by tadhg-moore** [comment]
It would be good to add an argument for suppressing model output to prevent printing to console eating RAM in Windows and also potential debugging in parallelization.

**Comment by jorritmesman** [comment]
Since this Issue relates to improving the calibration procedure and not to errors in the current code, we decided to move this topic to the "Refactoring calibration scripts" project in the Project Tracker and close the Issue.
