### ISSUE TITLE
check for model names

### ISSUE THREAD

**Issue by JFeldbauer** [aemon-j/LakeEnsemblR#79]
at the moment it is possible to enter wrong model names in "run_ensemble" which will lead to an error. We should add a check to see if all entries in the model argument are allowed

**Comment by jorritmesman** [comment]
A check and early failure of the code would work (stop() ). 

However, if we think that capital letters are the only common error and we don't want to punish users directly for that, we could also include an if-statement before the stop(), checking if the user might have meant a certain model (e.g. if(tolower(model[i] == "mylake"){model[i] = "MyLake"), continue the code and pass a warning instead
