### ISSUE TITLE
How should errors be handled?

### ISSUE THREAD

**Issue by tadhg-moore** [aemon-j/LakeEnsemblR#80]
Currently we do not have any checks or informative error/warning messages. It is important if the package is to be 'user-friendly' that we produce informative error messages with potential solutions to potential problems. It would be good to develop a philosophy for
1. Checking for errors e.g. argument, calculations
2. How to handle errors i.e. continue or abort the function
3. How this information is relayed to the user i.e tell them what doesn't work or should we include suggestions for fixes?
Add ideas and comments and also any errors you have had and potential fixes that you think would be useful.

**Comment by tadhg-moore** [comment]
I think the first step would to have argument checks at the beginning of each function. This will ensure that the 'input' is correct, i.e. ensure they are the right classes, check if files exist, check if model names are supported.

**Comment by jorritmesman** [comment]
I agree that this is a good start!

Would making a "check_master_config" function help, that we can run at the start of each function that takes the master config file? This might solve some issues (wrong time format, wrong input type (e.g. non-integer, string instead of numeric), pointing to non-existent files...).

**Comment by tadhg-moore** [comment]
That would be a great idea as the config file is the critical key to everything.

**Comment by jread-usgs** [comment]
Also to add to this - whenever we have functions that modify a user's environment (e.g., working directories or plotting defaults) we need to clean those up and reset when an error is encountered. I usually do an `on.exit()` for this kind of thing, and I think the package already has some of those in it.
