### ISSUE TITLE
Some of the models don't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by JFeldbauer** [aemon-j/LakeEnsemblR#96]
At least GLM and GOTM don't work in Ubuntu 16.04 because some shared libraries are missing

**Comment by jread-usgs** [comment]
yes, I ran into this too on my VM. I think it is libc2?

**Comment by JFeldbauer** [comment]
with me it was libnetcdf.so.13 (amongst others). I tried to update Travis to Ubuntu 18.04 but for R this is not possible at the moment: https://travis-ci.community/t/for-dist-bionic-xenial-vm-is-used-instead-with-language-rust/4487

**Comment by jread-usgs** [comment]
Understood. This is one of the challenges with this package (LER) being the first CI check of whether all five of the models run. Ideally, GLM3r (and the other packages) would have its own travis check, and figure out the shared libraries in that repository (including the system installs). I'm still on Ubuntu 16.04 for my VM, and I wonder how many other users aren't up to 18 yet.

**Comment by JFeldbauer** [comment]
Yeah it is a little bit complicated. I tried to include the missing shared libraries in the GLM3r package but just ran into more problems. As far as I understand it (which is limited) the best solution would be that the model packages (GLM3r, GOTMr, ...) just ship the source code of the models along with build instructions and then the models are compiled "locally"?

**Comment by jread-usgs** [comment]
Or one other option would be docker, but that comes with other challenges for new users. I know @robertladwig and Hilary have put a lot of thought into making GLM more accessible, so they probably have additional ideas.

**Comment by robertladwig** [comment]
Does this mean Travis will occasionally fail when it's using a 16.04 build?
The problem with docker is that it only works for certain Windows distributions, see: "Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later)." I guess most users have some Home edition, so docker won't work for them. But for Travis we could create a docker solution, but I don't know if this is reasonable.

**Comment by robertladwig** [comment]
With Johannes recent commits to SimstratR, GOTMr, FLakeR and GLM3r the models should now work on 16.04 (and most other Linux distributions).
